/**
 * HACKATHON NOVA CEREMONY CONTROLLER
 * Author: Generated by Antigravity
 * License: MIT
 */

/* =========================================
   1. CONFIGURATION
   ========================================= */
const CONFIG = {
    EVENT_LABEL: "HACKATHON NOVA",
    HOLD_SECONDS_AFTER_GO: 12,
    AUTO_FULLSCREEN: true,
    PLAY_AUDIO_ON_GESTURE: true,
    BRAND_RED: "#C8102E",
    PREFERS_REDUCED_MOTION: window.matchMedia('(prefers-reduced-motion: reduce)').matches,

    // Target Date
    // PRODUCTION DATE: January 26, 2026 at 9:00 AM Nepal Time
    // TARGET_DATE: new Date("2026-01-26T09:00:00+05:45"), 
    
    // Testing Config (Commented out for production)
    TEST_DURATION_MS: 15000, // 15 seconds
    TARGET_DATE: new Date(), // Set in init
    
    AUTO_TRIGGER_AT_ZERO: true, // Manual trigger only for safety
    state: 'PREP', // PREP | IMPACT | CELEBRATE | SETTLE
    mottos: [
        "Innovate. Create. Elevate.",
        "Code the Future.",
        "48 Hours of Brilliance.",
        "Welcome to the Arena."
    ]
};

/* =========================================
   2. DOM ELEMENTS
   ========================================= */
/* =========================================
   2. DOM ELEMENTS (Initialized in init)
   ========================================= */
let UI = {};

// Audio Context
let audioCtx = null;
let audioUnlocked = false;

/* =========================================
   3. INITIALIZATION
   ========================================= */
function init() {
    console.log("Ceremony Controller v2.1 (FIXED STARTUP) Initializing...");
    
    // Initialize UI Elements
    UI = {
        stage: document.getElementById('stage'),
        mainTitle: document.getElementById('main-title'),
        subtitle: document.getElementById('subtitle'),
        impactFlash: document.getElementById('impact-flash'),
        impactWord: document.getElementById('impact-word'),
        settleInfo: document.getElementById('settle-info'),
        mottoBox: document.getElementById('motto-box'),
        liveBadge: document.getElementById('live-badge'),
        
        // Countdown
        cd: document.getElementById('countdown'),
        cdH: document.getElementById('cd-h'),
        cdM: document.getElementById('cd-m'),
        cdS: document.getElementById('cd-s'),
    
        adminOverlay: document.getElementById('admin-overlay'),
        adminStatus: document.getElementById('admin-status'),
        fsFallback: document.getElementById('fs-fallback'),
        btnEnterFs: document.getElementById('btn-enter-fs')
    };

    // Sanity Check
    if (!UI.cd) {
        console.error("CRITICAL: Countdown element not found. Please ensure index.html matches the script expectations.");
        // Try to recover or warn
    }

    console.log("UI Initialized");
    
    // Interaction Listeners (Unlock Audio / Fullscreen)
    ['click', 'keydown', 'touchstart'].forEach(e => 
        window.addEventListener(e, handleInteraction, { once: true })
    );

    // Keyboard Shortcuts
    window.addEventListener('keydown', handleKeyEntry);
    
    // Fullscreen Button
    if (UI.btnEnterFs) UI.btnEnterFs.addEventListener('click', enterFullscreen);

    // Initial Render
    renderState();

    // Loop
    requestAnimationFrame(loop);

    // Init Target Date
    // For Production: CONFIG.TARGET_DATE = new Date("2026-01-14T...")
    // For Testing:
    CONFIG.TARGET_DATE = new Date(Date.now() + CONFIG.TEST_DURATION_MS);

    // Wake Lock
    requestWakeLock();
}

function handleInteraction() {
    if (!audioCtx) audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    if (audioCtx.state === 'suspended') audioCtx.resume();
    audioUnlocked = true;
    
    if (CONFIG.AUTO_FULLSCREEN) enterFullscreen();
    console.log("Audio Unlocked / Interaction Logged");
}

function loop() {
    // Only needed for confetti or time-based motto rotation if manual
    // Using CSS for main anims
    
    if (CONFIG.state === 'PREP') {
        updateCountdown();
    }

    requestAnimationFrame(loop);
}

function updateCountdown() {
    const diff = CONFIG.TARGET_DATE - new Date();
    
    if (diff <= 0) {
        UI.cd.innerText = "00:00:00";
        if (CONFIG.AUTO_TRIGGER_AT_ZERO) {
            triggerSequence();
        }
        return;
    }

    const h = Math.floor(diff / 3600000);
    const m = Math.floor((diff % 3600000) / 60000);
    const s = Math.floor((diff % 60000) / 1000);

    UI.cdH.innerText = String(h).padStart(2,'0');
    UI.cdM.innerText = String(m).padStart(2,'0');
    UI.cdS.innerText = String(s).padStart(2,'0');
}

/* =========================================
   4. STATE MACHINE & SEQUENCE
   ========================================= */

async function triggerSequence() {
    if (CONFIG.state !== 'PREP') return;
    
    console.log("TRIGGERING IMPACT SEQUENCE...");
    setConfigState('IMPACT');
    
    // 1. BLACKOUT (Pre-Impact)
    UI.impactFlash.style.background = 'black';
    UI.impactFlash.classList.remove('hidden');
    UI.impactWord.classList.add('hidden'); // Hide word initially
    
    announceARIA("Attention. Starting now.");

    // Wait 400ms Black
    await wait(400);

    // 2. FLASH "NOW."
    UI.impactWord.classList.remove('hidden');
    UI.impactWord.innerText = "NOW.";
    // Play Click/Tick sound here? Maybe a sharp inhale.
    playTickSound(); 

    // Wait 350ms on "NOW."
    await wait(350);

    // 3. RELEASE (GO)
    UI.impactFlash.classList.add('hidden'); // Clear overlay
    
    // Animate Title
    UI.mainTitle.innerText = `🚀 ${CONFIG.EVENT_LABEL}`;
    UI.mainTitle.className = 'animate-impact'; // Triggers CSS anim
    
    // Subtitle
    UI.subtitle.innerText = "HAS OFFICIALLY BEGUN";
    UI.subtitle.className = 'subtitle-go';

    // Badge
    UI.liveBadge.classList.remove('hidden');

    // Confetti & Audio
    startConfetti(); 
    playGoSound();
    announceARIA("Hackathon Nova has officially begun!");

    setConfigState('CELEBRATE');

    // 4. HOLD -> SETTLE
    setTimeout(() => {
        transitionToSettle();
    }, CONFIG.HOLD_SECONDS_AFTER_GO * 1000);
}

function transitionToSettle() {
    console.log("Settling...");
    setConfigState('SETTLE');
    
    // Show Info
    UI.settleInfo.classList.remove('hidden');
    
    // Start Motto Rotation
    startMottoRotation();

    // Stop Confetti gracefully
    // Confetti logic handles its own stop after duration, but we ensure it here
    // Our confetti automatically stops after ~8s in render loop, so it matches.
}

function setConfigState(newState) {
    CONFIG.state = newState;
    UI.adminStatus.innerText = newState;
}

function renderState() {
    // Reset visual to PREP
    if (CONFIG.state === 'PREP') {
        UI.mainTitle.innerText = CONFIG.EVENT_LABEL;
        UI.mainTitle.className = 'title-prep';
        UI.subtitle.innerText = "OPENING CEREMONY";
        UI.subtitle.className = 'subtitle-prep';
        UI.cd.classList.remove('hidden'); // Show timer
        UI.liveBadge.classList.add('hidden');
        UI.impactFlash.classList.add('hidden');
        UI.settleInfo.classList.add('hidden');
        document.body.style.backgroundColor = ''; // Reset
        stopConfetti();
    } else {
        // Hide timer in all other states
        UI.cd.classList.add('hidden');
    }
}

/* =========================================
   5. ADMIN CONTROLS
   ========================================= */
function handleKeyEntry(e) {
    const key = e.key.toUpperCase();
    
    // Unlock audio if key pressed
    handleInteraction();

    switch(key) {
        case 'G':
            if (CONFIG.state === 'PREP') triggerSequence();
            break;
        case 'R':
            if (confirm("Reset to PREP?")) {
                setConfigState('PREP');
                // Reset timer for testing
                CONFIG.TARGET_DATE = new Date(Date.now() + CONFIG.TEST_DURATION_MS);
                renderState();
            }
            break;
        case 'F':
            enterFullscreen();
            break;
        case 'H':
            UI.adminOverlay.classList.toggle('hidden');
            break;
        case ' ': // Space
             // Could pause animations, but CSS animations are hard to pause mid-flight.
             // We'll log a marker.
             console.log("Marker set");
             break;
    }
}

/* =========================================
   6. AUDIO SYNTHESIS (Cinematic)
   ========================================= */
function playTickSound() {
    // Sharp "Woodblock" tick for NOW.
    if (!audioUnlocked || CONFIG.PREFERS_REDUCED_MOTION) return;
    const osc = audioCtx.createOscillator();
    const gain = audioCtx.createGain();
    
    osc.type = 'square';
    osc.frequency.setValueAtTime(800, audioCtx.currentTime);
    osc.frequency.exponentialRampToValueAtTime(100, audioCtx.currentTime + 0.1);
    
    gain.gain.setValueAtTime(0.3, audioCtx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.01, audioCtx.currentTime + 0.1);
    
    osc.connect(gain);
    gain.connect(audioCtx.destination);
    osc.start();
    osc.stop(audioCtx.currentTime + 0.15);
}

function playGoSound() {
    // Massive Cinematic Boom + Chord
    if (!audioUnlocked || CONFIG.PREFERS_REDUCED_MOTION) return;
    const now = audioCtx.currentTime;
    
    // 1. Kick / Sub Drop
    const sub = audioCtx.createOscillator();
    const subG = audioCtx.createGain();
    sub.frequency.setValueAtTime(150, now);
    sub.frequency.exponentialRampToValueAtTime(40, now + 1);
    subG.gain.setValueAtTime(1, now);
    subG.gain.exponentialRampToValueAtTime(0.01, now + 2);
    sub.connect(subG); subG.connect(audioCtx.destination);
    sub.start(); sub.stop(now + 2);

    // 2. Major Chord Swell (C Major)
    [261.63, 329.63, 392.00, 523.25].forEach((f, i) => {
        const osc = audioCtx.createOscillator();
        const g = audioCtx.createGain();
        osc.type = 'sawtooth';
        osc.frequency.value = f;
        osc.detune.value = Math.random() * 20 - 10;
        
        g.gain.setValueAtTime(0, now);
        g.gain.linearRampToValueAtTime(0.1, now + 0.1);
        g.gain.exponentialRampToValueAtTime(0.01, now + 4);
        
        const lpf = audioCtx.createBiquadFilter();
        lpf.type = 'lowpass';
        lpf.frequency.setValueAtTime(100, now);
        lpf.frequency.exponentialRampToValueAtTime(3000, now + 0.3);

        osc.connect(lpf); lpf.connect(g); g.connect(audioCtx.destination);
        osc.start(); osc.stop(now + 4);
    });
}

/* =========================================
   7. VISUALS (Confetti & Motto)
   ========================================= */
// Motto Rotation
let mottoIdx = 0;
function startMottoRotation() {
    UI.mottoBox.innerText = CONFIG.mottos[0];
    setInterval(() => {
        mottoIdx = (mottoIdx + 1) % CONFIG.mottos.length;
        UI.mottoBox.innerText = CONFIG.mottos[mottoIdx];
        // Could add fade transition logic here
    }, 6000);
}

// Confetti (Optimized, Directional)
const cvs = document.getElementById('confetti-canvas');
const ctx = cvs.getContext('2d');
let particles = [];

function resize() { cvs.width = window.innerWidth; cvs.height = window.innerHeight; }
window.addEventListener('resize', resize); resize();

function startConfetti() {
    if (CONFIG.PREFERS_REDUCED_MOTION) return;
    
    // Top Left & Top Right Bursts
    for(let i=0; i<75; i++) createParticle(0, 0, 2, 5); // TL
    for(let i=0; i<75; i++) createParticle(cvs.width, 0, -2, 5); // TR

    animateConfetti();
}

function createParticle(x, y, vxBase, vyBase) {
    particles.push({
        x: x, y: y,
        vx: vxBase + (Math.random() * 10 - 5),
        vy: vyBase + (Math.random() * 10),
        color: `hsl(${Math.random()*360}, 100%, 50%)`,
        size: Math.random() * 8 + 4,
        life: 1.0,
        decay: Math.random() * 0.01 + 0.005
    });
}

function animateConfetti() {
    if (particles.length === 0) return;
    
    ctx.clearRect(0,0,cvs.width, cvs.height);
    
    for(let i=0; i<particles.length; i++) {
        let p = particles[i];
        p.x += p.vx;
        p.y += p.vy;
        p.life -= p.decay;
        p.vx *= 0.99; // Air resistance
        
        ctx.fillStyle = p.color;
        ctx.globalAlpha = p.life;
        ctx.fillRect(p.x, p.y, p.size, p.size);
    }
    
    // Remove dead
    particles = particles.filter(p => p.life > 0);
    ctx.globalAlpha = 1;

    requestAnimationFrame(animateConfetti);
}

function stopConfetti() {
    particles = [];
    ctx.clearRect(0,0,cvs.width, cvs.height);
}

/* =========================================
   8. UTILS
   ========================================= */
function wait(ms) { return new Promise(r => setTimeout(r, ms)); }
function announceARIA(msg) { console.log("ARIA:", msg); /* Implementation imply aria-live div if separate needed */ }

function enterFullscreen() {
    document.documentElement.requestFullscreen().then(() => {
        UI.fsFallback.classList.add('hidden');
    }).catch(e => {
        console.warn("FS Blocked", e);
        UI.fsFallback.classList.remove('hidden');
    });
}

async function requestWakeLock() {
    try { if('wakeLock' in navigator) await navigator.wakeLock.request('screen'); }
    catch(e) {}
}

// Start
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
} else {
    init();
}
